# Site Settings
lang: en
title: Bailey3D
tagline: Technical Art
email: contact@bailey3d.com
description: >
  Technical Artist - Specialising in Pipeline, Tools, and Shaders.
baseurl: ""
url: "https://www.bailey3d.com"
permalink: pretty
favicon: "/assets/images/B3D_Logo.png"
hero_image: /assets/images/banner.jpg
#hide_share_buttons: true 
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
remote_theme: chrisrhymes/bulma-clean-theme

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Bailey Martin"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
  -
    scope:
      path: ""
      type: "products"
    values:
      author: "Bailey Martin"
      layout: product
      image: https://via.placeholder.com/800x600
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

  docs:
    output: true
    permalink: /:collection/:path/
    layout: page
    image: https://via.placeholder.com/800x600
    show_sidebar: false


# This list contains information on the store entries
# - The order of the list determines the order of the products in the store page and in store sidebars
# - The name must be added to a given blog post via a key (e.g. `store_name: iridescent_materials`)
store:
  iridescent_materials:
    price: $24.99
    buy_now_link: https://www.unrealengine.com/marketplace/en-US/product/iridescent-pearlescent-materials-pack
    rating: 5

  retro_filters_pack:
    price: $34.99
    buy_now_link: https://www.unrealengine.com/marketplace/en-US/product/iridescent-pearlescent-materials-pack

  sketch_it:
    price: $23.99
    docs_link: /docs/SketchIt/index
    buy_now_link: https://www.unrealengine.com/marketplace/en-US/product/sketchit-post-process-pack
    rating: 5

  mesh_splitter:
    price: Free
    buy_now_link: https://www.artstation.com/a/14426803

  quick_merge_selection:
    price: $4.99
    buy_now_link: https://www.artstation.com/a/15216332
  

# This list contains information on the portfolio / homepage entries
# - The order of the list determines the order on the homepage
# - The name must be added to a given blog post via a key (e.g. `portfolio: space_colonization`)
portfolio:
  space_colonization:
    example: 0
  hlsl_shader_unreal:
    example: 0
  ocean_rendering:
    example: 0
  juniper:
    example: 0
  desert_diorama:
    example: 0
  houidini_drop:
    example: 0
  iridescent_shader:
    example: 0